service: image-service

custom:
  bucket: user-profile-images-lalalalaxxx

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: us-west-1
  environment:
    BUCKET: ${self:custom.bucket}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"

functions:
  save:
    handler: handler.save
    events:
      - http:
          path: save-image
          method: post
          cors: true
  notify:
    handler: handler.notify
    # handler: image-resize.resizeImage
    events:
      - s3:
          bucket: ${self:custom.bucket}
          event: s3:ObjectCreated:*
  # resizeImage:
  #   handler: image-resize.resizeImage
  #   events:
  #     - http:
  #         path: resize-image
  #         method: post
  #         cors: true

# We need an additional bucket without a listener
resources:
  Resources:
    UploadBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucket}-output
        AccessControl: PublicRead
        CorsConfiguration:
          CorsRules:
          - AllowedMethods:
            - GET
            - PUT
            - POST
            - HEAD
            AllowedOrigins:
            - "*"
            AllowedHeaders:
            - "*"
